setxkbmap br &

unclutter --timeout 1 &
numlockx &

xset r rate 200 50 &
eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_ed25519 &
imwheel &

feh --no-fehbg --bg-fill ~/Documents/Images/Wallpapers/grey_bird.jpg &
/usr/src/dwm-bar/dwm_bar.sh &

exec dwm

