#!/bin/sh

# bashrc setup.

# Dependencies: Script for git integration must be in ~/Scripts

# See:
# https://www.gnu.org/software/bash/manual/html_node/Controlling-the-Prompt.html
# ANSI escape code
# https://unix.stackexchange.com/questions/124407/what-color-codes-can-i-use-in-my-bash-ps1-prompt
# https://stackoverflow.com/questions/4842424/list-of-ansi-color-escape-sequences
# https://www.git-scm.com/book/en/v2/Appendix-A%3A-Git-in-Other-Environments-Git-in-Bash
# https://blog.backslasher.net/git-prompt-variables.html

# Objectives:

#       ~/Projects/serenity | master +
#       > ls

#   1. Nice prompt.                                        DONE
#       1.1 Current dir full path.                         DONE in ~/.bashrc
#       1.2 Colorful                                       DONE in ~/.bashrc
#       1.3 git integration                                DONE in ~/.bashrc

#   2. Case-insentive tab completion                       DONE in ~/.bashrc
#   3. Incremental history search                          DONE in ~/.bashrc

#   4. Color hint for available or unavailable command?
#   5. Command prediction?
#   6. Return success and failure output?

