#!/bin/sh
# Author:    Matheus Vinicius <matheusvinicius7000@gmail.com>

PACKAGES=( # list of packages to be installed

#                           COMPRESSION

# p7zip
# unzip
# zip


#                           DEVELOPMENT

# android-tools
# android-udev
  autoconf
  automake
  binutils
  bison
  ccache                # caches c/c++ compiling info
  cmake
# code                  # vscode oss version
  gcc                   # compiler
  flex
  git
# java-environment-common
# java-runtime-common
# jdk11-openjdk
# jre11-openjdk
  m4
  make
# maven
# npm
# pacman-contrib
  pax-utils
  pkgconf
  patch


#                           DRIVERS

# lib32-mesa            # these three are only necessary for gaming
# lib32-vulkan-radeon
# vulkan-radeon
  xf86-video-amdgpu     # basic video driver


#                           DWM CONFIG.H DEPENDENCIES

  acpilight             # controls display brightness
  picom                 # compositor
  pulseaudio            # pactl controls audio
  scrot                 # simple screenshot tool
  ttf-hack              # hack font
  unclutter             # hides mouse


#                           FILES

# pcmanfm               # lightweight gui file manager
# ranger                # cli file manager written in python
# tree                  # print file structure tree -d path
# rsync


#                           IMAGE/VIDEO

  feh
# gimp
# mpv
# obs-studio


#                           INTERNET

# firefox
# transmission-cli
# webkit2gtk


#                           LIBRARIES

  libx11                # keyboard functions
# libxft                # special chars
  libxinerama           # multi-monitor
  libtool               # don't know what it does, but it is probably important


#                           PDF

# zathura
# zathura-pdf-mupdf


#                           ROOT

# doas                  # actually better than sudo
  fakeroot
# sudo


#                           SHELL

# zsh                   # i also use oh-my-zsh, je suis désolé
# zsh-completions
  which


#                           SOUND

# openal                # 3d audio, whatever that means
# pamixer
# pulsemixer
# sof-firmware          # install in case of problems


#                           SYSTEM DEPENDENCIES (probably already installed)

  base
  efibootmgr
  grub
  linux
  linux-firmware
# networkmanager


#                           SYSTEM TRACE

  htop
# ncdu


#                           TEXT/DOCS

  groff
  man-db
# openjdk11-doc
# openjdk11-src
  texinfo
  vim


#                           VIRTUALIZATION

# dnsmasq
# edk2-ovmf
# iptables-nft
# libvirt
# lxsession
# qemu
# qemu-arch-extra
# virt-manager


#                           X PACKAGES

# xorg-fonts-alias-100dpi   # install these in case of font problems
# xorg-fonts-alias-75dpi
# xorg-fonts-misc
  xorg-xsetroot         # prints status bar
  xorg-server           # main package for x
  xorg-xinit            # inits x and wm
  xorg-xrandr           # resolution configs


)

if [ "$EUID" -ne 0 ] # root validation
    then printf "Only root user can perform this operation.\n\n"
    exit
fi

pacman -Syyyu --noconfirm # update packages

for (( i = 0; i < ${#PACKAGES[@]}; i++ )) # install packages
do
    package=${PACKAGES[$i]}
    pacman -S --noconfirm $package
done
