#!/bin/sh
# Author:    Matheus Vinicius <matheusvinicius7000@gmail.com>

PACKAGES=( # list of packages to be installed

acpilight
# android-tools
# android-udev
# autoconf
# automake
base
# binutils
# bison
# ccache
# cmake
# code
# dnsmasq
# edk2-ovmf
efibootmgr
fakeroot
# feh
# firefox
# flex
gcc
# gimp
git
groff
grub
htop
# iptables-nft
# java-environment-common
# java-runtime-common
# jdk11-openjdk
# jre11-openjdk
# lib32-mesa
# lib32-vulkan-radeon
libtool
# libvirt
libx11
libxft
libxinerama
linux
linux-firmware
# lxsession
# m4
make
man-db
# maven
# mpv
# ncdu
# networkmanager
# npm
# obs-studio
# openal
# openjdk11-doc
# openjdk11-src
# p7zip
# pacman-contrib
pamixer
patch
# pax-utils
# pcmanfm
picom
# pkgconf
pulseaudio
# pulsemixer
# qemu
# qemu-arch-extra
# ranger
# rsync
scrot
# sof-firmware
# sudo
# texinfo
# transmission-cli
ttf-hack
unclutter
# unzip
vim
# virt-manager
# vulkan-radeon
# webkit2gtk
# which
xf86-video-amdgpu
# xorg-fonts-alias-100dpi
# xorg-fonts-alias-75dpi
# xorg-fonts-misc
xorg-server
xorg-xinit
xorg-xrandr
xorg-xsetroot
# zathura
# zathura-pdf-mupdf
# zip
# zsh
# zsh-completions

)

if [ "$EUID" -ne 0 ] # Update System
then
    echo 'Y' | sudo pacman -Syyyu
else
    echo 'Y' | pacman -Syyyu
fi

for (( i = 0; i < ${#PACKAGES[@]}; i++ )) # Install Packages
do
    package=${PACKAGES[$i]}
    
    if [ "$EUID" -ne 0 ]
    then
        echo 'Y' | sudo pacman -S $package
    else
        echo 'Y' | pacman -S $package
    fi
done
